### ISSUE TITLE
Typos not annotated as such

### ISSUE THREAD

**Issue by rhdunn** [UniversalDependencies/UD_English-GENTLE#11]
The following are missing `CorrectForm` and `Typo=Yes` annotations:
```
ERROR: Sentence GENTLE_threat_malik-4 token 10 -- DT lemma 'no' does not match lowercase-form applied to form 'know', expected 'know'
ERROR: Sentence GENTLE_threat_bolin-2 token 16 -- RB lemma 'too' does not match lowercase-form applied to form 'to', expected 'to'
ERROR: Sentence GENTLE_threat_kelly-14 token 4 -- VB lemma 'hear' does not match lowercase-form applied to form 'here', expected 'here'
ERROR: Sentence GENTLE_threat_malik-4 token 8 -- MD lemma 'would' does not match lowercase-form applied to form ''ed', expected ''ed'
```

Isn't the following supposed to be an initialism for "Private Investigator" instead of a typo?:
```
ERROR: Sentence GENTLE_threat_bolin-9 token 1 -- PRP lemma 'I' does not match lowercase-form applied to form 'PI', expected 'pi'
```

**Comment by amir-zeldes** [comment]
The second case actually has CorrectForm and Typo in the data:

https://github.com/UniversalDependencies/UD_English-GENTLE/blob/master/not-to-release/sources/GENTLE_threat_bolin.conllu#L346

The last case is ambiguous. The digitized text we have has that P in it, but the official court documents don't have it. I can't tell if it was introduced during digitization, or if the court normalized it away:

https://scocal.stanford.edu/opinion/people-v-bolin-31391

In any case, I'd like to be consistent with the official record of this threat letter, so I'll go with interpreting it as a typo for "I" (there is also no other mention of a detective in the document).

Fixed the others.
