### ISSUE TITLE
Missing CorrectForm and Typo annotations in multi-word tokens

### ISSUE THREAD

**Issue by rhdunn** [UniversalDependencies/UD_English-GENTLE#2]
The following multi-word tokens are missing CorrectForm/Typo annotations, or have incorrect lemmas:
```
ERROR: Sentence GENTLE_esports_fortnite-39 token 7-8 -- unrecognized multi-word token form 'JarkoS''
ERROR: Sentence GENTLE_esports_fortnite-59 token 14 -- unexpected multi-word token 'you've' part lemma 'be', expected 'have'
ERROR: Sentence GENTLE_threat_malik-2 token 83-84 -- unrecognized multi-word token form 'thats'
ERROR: Sentence GENTLE_threat_malik-7 token 25-26 -- unrecognized multi-word token form 'thats'
```

**Comment by amir-zeldes** [comment]
GENTLE_esports_fortnite-59 indeed has a lemma error, which should now be fixed upstream, and GENTLE_threat_malik was missing error annotations - thanks for reporting. GENTLE_esports_fortnite-39 seems correct to me, since genitive 's is generally taken to for a MWT, no?

**Comment by rhdunn** [comment]
Thanks for the fixes.

The GENTLE_esports_fortnite-39 MWT is indeed correct. My script is matching `s'` to avoid picking up other MWTs with `'` at the end. My code was not detecting capitalized suffix forms, so was not matching that example. I've updated my script so it is no longer reporting that MWT as an issue.
